################################################################################
#
# Set JAVA IFACE for SC
#
- name: Set JAVA IFACE | SC | NOVLAN
  set_fact: java_iface="{{ 'ansible_' + hostvars[item]['vnet_java'] }}"
  with_items:
  - "{{ groups.sc }}"
  when:
  - not use_vlans
  - inventory_hostname in groups.sc
  - not inventory_hostname in groups.java_fe
  - inventory_hostname == "{{ item }}"
  tags:
  - initialization

- name: Set JAVA IFACE | SC | VLAN
  set_fact: java_iface="{{ 'ansible_' + "%s.%d"|format(hostvars[item]['vnet_java'], hostvars[item]['vlan_tag']) }}"
  with_items:
  - "{{ groups.sc }}"
  when:
  - inventory_hostname == "{{ item }}"
  - use_vlans
  - inventory_hostname in groups.sc
  tags:
  - initialization
