---
# CC INIT

- name: Set CC IFACE | No VLAN
  set_fact: cc_iface="{{ 'ansible_' + hostvars[item]['vnet_public']  }}"
  with_items:
  - "{{ groups.cc }}"
  when:
  - not use_vlans
  - inventory_hostname == "{{ item }}"
  tags:
  - initialization

- name: Set CC IFACE | VLAN
  set_fact: cc_iface="{{  'ansible_' + "%s.%d"|format(hostvars[item]['vnet_public'],  hostvars[item]['vlan_tag'])  }}"
  with_items:
  - "{{ groups.cc }}"
  when:
  - use_vlans
  - inventory_hostname == "{{ item }}"
  tags:
  - initialization

- name: Generate ssh-key on CC
  user: generate_ssh_key=yes ssh_key_bits=4096 ssh_key_passphrase= name=root
  register: cc_public_key
  tags:
  - initialization
  - cc_keys

- name: Deploy CC ssh key on CC
  authorized_key: user=root state=present key="{{ cc_public_key.ssh_public_key }}"
  tags:
  - initialization
  - cc_keys

- name: Config CC ssh config on CC
  copy: src=ssh_config dest=/root/.ssh/config
  tags:
  - initialization
  - config

- name: Import CC(s) public key on ansible machine
  fetch: src=/root/.ssh/id_rsa.pub dest="/var/tmp/cc-{{ hostvars[item]['partition'] }}" flat=yes
  when:
  - partition == "{{ hostvars[item]['partition'] }}"
  with_items: "{{ groups.cc }}"
  tags:
  - initialization
  - config
  - cc_keys

- name: Authorize CLC SSH Key on CC
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
  tags:
  - initialization
  - clc_keys
