---
# CC INIT

- name: Set CC IFACE | No VLAN
  set_fact: cc_iface="{{ hostvars[item]['ansible_' + hostvars[item]['vnet_public']]  }}"
  when:
  - not use_vlans
  - networking_mode == "EDGE"
  tags:
  - initialization

- name: Set CC IFACE | VLAN
  set_fact: cc_iface="{{  hostvars[item]['ansible_' + "%s.%d"|format(hostvars[item]['vnet_public'],  hostvars[item]['vlan_tag'])]  }}"
  when:
  - use_vlans
  - networking_mode == "MANAGED-NOVLAN"
  tags:
  - initialization

- name: Generate ssh-key on CC
  user: generate_ssh_key=yes ssh_key_bits=4096 ssh_key_passphrase= name=root
  register: cc_public_key
  tags:
  - initialization
  - cc_keys

- name: Deploy CC ssh key
  authorized_key: user=root state=present key="{{ cc_public_key.ssh_public_key }}"
  tags:
  - initialization
  - cc_keys

- name: Config CC ssh config
  copy: src=ssh_config dest=/root/.ssh/config
  tags:
  - initialization
  - config

- name: Import CC(s) public key
  fetch: src=/root/.ssh/id_rsa.pub dest="/var/tmp/cc-{{ hostvars[item]['partition'] }}" flat=yes
  with_items: "{{ groups.cc }}"
  tags:
  - initialization
  - config
  - cc_keys

- name: Authorize CLC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
  tags:
  - initialization
  - clc_keys
