---
# INIT Eucalyptus configuration file

- name: Define vCPU overcommit
  shell: echo "{{ ansible_processor_vcpus }} * {{ cpu_overcommit }}" | bc
  register: nc_vcpu
  tags:
  - init_config
  - overcommit
  when:
  - inventory_hostname in "{{ groups.nc }}"

- name: configure eucalyptus.conf
  template: src=eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf
  tags:
  - init_config
