################################################################################
#
# JAVA Front-Ends
#

- name: Set JAVA IFACE | No VLAN
  set_fact: java_iface="{{  'ansible_' + hostvars[item]['vnet_java'] }}"
  with_items:
  - "{{ groups.java_fe }}"
  when:
  - not use_vlans
  tags:
  - initialization

- name: Set JAVA IFACE | VLAN
  set_fact: java_iface="{{ 'ansible_' + "%s.%d"|format(hostvars[item]['vnet_java'], hostvars[item]['vlan_tag']) }}"
  with_items:
  - "{{ groups.java_fe }}"
  when:
  - use_vlans
  tags:
  - initialization

- name: Authorize CLC SSH Key
  authorized_key: user=root key="{{ lookup('file', '/var/tmp/clc-pub-key') }}"
  tags:
  - initialization
  - clc_keys
