################################################################################
#
# Cloud initialization process
#

- name: Generate ssh-key on CLC
  user: generate_ssh_key=yes ssh_key_bits=4096 ssh_key_passphrase= name=root
  register: clc_public_key
  tags:
  - clc
  - config

- name: Deploy CLC public_key
  authorized_key: user=root state=present key="{{ clc_public_key.ssh_public_key }}"
  tags:
  - clc
  - config

- name: Config CLC ssh config
  copy: src=ssh_config dest=/root/.ssh/config
  tags:
  - clc
  - config

- name: Getting CLC public key to Ansible host
  fetch: src=/root/.ssh/id_rsa.pub dest=/var/tmp/clc-pub-key flat=yes
  tags:
  - clc
  - config

- name: create the EDGE config
  template: src=network.json.j2 dest="{{ edge_network_config_file }}"
  tags:
  - initialization
  - configure
  when:
  - networking_mode == "EDGE"

- name: Set JAVA IFACE | CLC |  No VLAN
  set_fact: java_iface="{{ 'ansible_' + hostvars[item]['vnet_java'] }}"
  with_items:
  - "{{ groups.clc }}"
  when:
  - inventory_hostname == "{{ item }}"
  - inventory_hostname in groups.clc
  - not inventory_hostname in groups.java_fe
  - not use_vlans
  tags:
  - initialization

- name: Set JAVA IFACE | CLC | VLAN
  set_fact: java_iface="{{ 'ansible_' + "%s.%d"|format(hostvars[item]['vnet_java'], hostvars[item]['vlan_tag']) }}"
  with_items:
  - "{{ groups.clc }}"
  when:
  - use_vlans
  - inventory_hostname == "{{ item }}"
  - inventory_hostname in groups.clc
  - not inventory_hostname in groups.java_fe
  tags:
  - initialization
