---
# tasks file for eucalyptus-initialize

- include: init-clc.yml
  when:
  - inventory_hostname in groups.clc
  tags:
  - initialization

- include: init-java_fe.yml
  when:
  - inventory_hostname in groups.java_fe
  tags:
  - initialization

- include: init-cc.yml
  when:
  - inventory_hostname in groups.cc
  tags:
  - initialization

- include: init-nc.yml
  when:
  - inventory_hostname in groups.nc
  tags:
  - initialization

- include: init-config.yml
  tags:
  - initialization
