---
# tasks file for eucalyptus-initialize

- name: Init CLC
  include: init-clc.yml
  when:
  - inventory_hostname in groups.clc
  tags:
  - initialization

- name: Iniit JAVA compoents
  include: init-java_fe.yml
  when:
  - inventory_hostname in groups.java_fe
  tags:
  - initialization

- name: Init UFS
  include: init-sc.yml
  when:
  - inventory_hostname in groups.ufs
  tags:
  - initialization

- include: init-sc.yml
  when:
  - inventory_hostname in groups.sc
  tags:
  - initialization

- include: init-cc.yml
  when:
  - inventory_hostname in groups.cc
  tags:
  - initialization

- include: init-nc.yml
  when:
  - inventory_hostname in groups.nc
  tags:
  - initialization

- name: Debug JAVA iface
  debug: msg="{{ hostvars[item][hostvars[item]['java_iface']]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.java_fe }}"
  when:
  - inventory_hostname in groups.java_fe
  - not inventory_hostname in groups.sc
  - inventory_hostname == "{{ item }}"

- name: Debug SC JAVA iface
  debug: msg="{{ hostvars[item][hostvars[item]['java_iface']]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.java_fe }}"
  when:
  - inventory_hostname in groups.sc
  - not inventory_hostname in groups.java_fe
  - inventory_hostname == "{{ item }}"

- name: Debug CC iface
  debug: msg="{{ hostvars[item][hostvars[item]['cc_iface']]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.cc }}"
  when:
  - inventory_hostname in groups.cc
  - inventory_hostname == "{{ item }}"

- name: Debug NC iface
  debug: msg="{{ hostvars[item][hostvars[item]['nc_iface']]['ipv4']['address'] }}"
  with_items:
  - "{{ groups.nc }}"
  when:
  - inventory_hostname in groups.nc
  - inventory_hostname == "{{ item }}"

- include: init-config.yml
  tags:
  - initialization
